### ISSUE TITLE
Cannot read property name

### ISSUE THREAD

**Issue by hvadym** [k-egor-smirnov/node-tg-native#5]
![image](https://user-images.githubusercontent.com/15213317/34825959-516741a2-f6dd-11e7-9990-3910f15efb53.png)

code
```
const nodeTgNative = require("node-tg-native");
const td = new nodeTgNative();

td.create();

td.subscribe(response => {
  console.log(response);
});
```

node v7.0.0
npm v3.10.8

**Comment by k-egor-smirnov** [comment]
Please, update your node at least to 7.10.0 (I checked that on 7.0.0 and 7.10.0)
